{% set version = "0.0.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-patrick
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/patrick_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/patrick/patrick_{{ version }}.tar.gz
  sha256: 1191bf9af9dd768449a1883f34cd4087ec3a643edf1aebea9b1dbc8b1a1648ec

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-dplyr
    - r-purrr
    - r-rlang
    - r-testthat
    - r-tibble

  run:
    - r-base
    - r-dplyr
    - r-purrr
    - r-rlang
    - r-testthat
    - r-tibble

test:
  commands:
    - $R -e "library('patrick')"           # [not win]
    - "\"%R%\" -e \"library('patrick')\""  # [win]

about:
  home: https://github.com/google/patrick

  license: Apache-2.0
  license_file: LICENSE
  summary: This is an extension of the 'testthat' package that lets you add parameters to your unit tests. Parameterized unit tests are often easier to read and more reliable, since they follow the DNRY (do not repeat yourself) rule.

  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - michaelquinn32
